### ISSUE TITLE
Change the "Almost killed me" to something else...

### ISSUE THREAD

**Issue by BrickerBrickerOneNine** [calebtote/slackbots#5]
If a command would have legitimately killed the bot, sure. if its just informing you it cant properly handle the request, maybe the output should be different

**Comment by calebtote** [comment]
This currently the behavior of the bot - it only reports on legitimate crash scenarios. It's just that some of the basic exception logic hasn't been written (i.e., if we attempt to delete a title from the DB that doesn't exist, or if we issue a `@torbot fulfill` with no parameters)

**Comment by calebtote** [comment]
relates to: https://github.com/calebtote/slackbots/issues/6
